Repository vrtex-team/pytorch_geometric, pull requests merged in 2021-06, with the labels that each got.

#36 modify api for hete graph
  test/data/test_data.py
  test/data/test_hetero_data.py
  torch_geometric/data/data.py
  torch_geometric/data/hetero_data.py
  torch_geometric/data/in_memory_dataset.py
Labels: enhancement

#42 add comment and additional apis to the graph
  test/data/test_hetero_data.py
  torch_geometric/data/hetero_data.py
Labels: documentation

#43 Lazy GNN initialization for almost all GNN operators
  torch_geometric/nn/conv/cluster_gcn_conv.py
  torch_geometric/nn/conv/film_conv.py
  torch_geometric/nn/conv/gen_conv.py
  torch_geometric/nn/conv/le_conv.py
  torch_geometric/nn/conv/mf_conv.py
  torch_geometric/nn/conv/pan_conv.py
  torch_geometric/nn/conv/pna_conv.py
  torch_geometric/nn/conv/res_gated_graph_conv.py
  torch_geometric/nn/conv/sage_conv.py
  torch_geometric/nn/conv/sg_conv.py
  torch_geometric/nn/conv/signed_conv.py
  torch_geometric/nn/conv/transformer_conv.py
Labels: enhancement

#51 Fix Documentation Rendering
  docs/source/modules/nn.rst
  torch_geometric/data/hetero_data.py
  torch_geometric/nn/conv/general_conv.py
  torch_geometric/nn/conv/hgt_conv.py
  torch_geometric/nn/fx.py
  torch_geometric/nn/to_hetero.py
Labels: documentation

#50 Remove PyTorch 1.7.0 legacy code
  test/nn/conv/test_hgt_conv.py
  test/nn/dense/test_linear.py
  test/nn/test_to_hetero.py
  torch_geometric/nn/dense/linear.py
  torch_geometric/nn/fx.py
  torch_geometric/nn/to_hetero.py
Labels: bug / fix, enhancement

#44 Fix `copy.deepcopy` within lazy `nn.dense.Linear`
  test/nn/dense/test_linear.py
  test/nn/test_to_hetero.py
  torch_geometric/nn/dense/linear.py
  torch_geometric/nn/fx.py
  torch_geometric/nn/to_hetero.py
Labels: bug / fix

#40 HGT+DBLP Example
  examples/hetero/hgt_dblp.py
Labels: enhancement

#60 Add Figure and Equation to `to_hetero` docstring
  docs/source/_figures/to_hetero.svg
  docs/source/_figures/to_hetero.tex
  torch_geometric/nn/to_hetero.py
Labels: documentation

#53 Message Passing Hooks
  test/nn/conv/test_message_passing.py
  torch_geometric/nn/conv/message_passing.py
Labels: enhancement

#58 Rename `HeteroData.get_edges` and `HeteroData.get_nodes`
  test/data/test_hetero_data.py
  torch_geometric/data/hetero_data.py
Labels: bug / fix

#64 `HeteroConv`
  examples/hetero/hetero_conv_dblp.py
  torch_geometric/nn/conv/__init__.py
  torch_geometric/nn/conv/hetero_conv.py
Labels: enhancement
