Repository vrtex-team/pytorch_geometric, pull requests merged in 2021-08, with the labels that each got.

#73 Implementation of the `HGTLoader` + `ogbn-mag` example
  examples/hetero/to_hetero_mag.py
  test/data/test_hg_sampler.py
  torch_geometric/data/__init__.py
  torch_geometric/data/hg_sampler.py
  torch_geometric/datasets/ogb_mag.py
  torch_geometric/nn/conv/gat_conv.py
  torch_geometric/nn/to_hetero_transformer.py
  torch_geometric/nn/to_hetero_with_bases_transformer.py
  torch_geometric/transforms/to_sparse_tensor.py
  torch_geometric/utils/coalesce.py
Labels: enhancement

#72 Random split functionalities
  examples/link_pred.py
  test/transforms/test_random_link_split.py
  torch_geometric/data/dataset.py
  torch_geometric/transforms/__init__.py
  torch_geometric/transforms/compose.py
  torch_geometric/transforms/random_link_split.py
  torch_geometric/utils/negative_sampling.py
Labels: enhancement

#98 Improve `torch_geometric.data` Documentation
  docs/source/_static/css/custom.css
  docs/source/conf.py
  docs/source/modules/data.rst
  docs/source/notes/introduction.rst
  test/data/test_hetero_data.py
  torch_geometric/data/__init__.py
  torch_geometric/data/batch.py
  torch_geometric/data/data.py
  torch_geometric/data/dataset.py
  torch_geometric/data/download.py
  torch_geometric/data/extract.py
  torch_geometric/data/hetero_data.py
  torch_geometric/data/in_memory_dataset.py
  torch_geometric/data/storage.py
Labels: documentation

#103 `_parent` memory leak fix
  test/data/test_data.py
  test/data/test_hetero_data.py
  test/data/test_storage.py
  torch_geometric/data/data.py
  torch_geometric/data/hetero_data.py
  torch_geometric/data/storage.py
Labels: bug / fix

#92 (Heterogeneous) `NeighborLoader`
  docs/source/index.rst
  docs/source/modules/loader.rst
  examples/hetero/to_hetero_mag.py
  test/loader/test_neighbor_loader.py
  torch_geometric/__init__.py
  torch_geometric/data/hgt_sampler.py
  torch_geometric/datasets/ogb_mag.py
  torch_geometric/loader/__init__.py
  torch_geometric/loader/neighbor_loader.py
  torch_geometric/loader/utils.py
  torch_geometric/transforms/to_undirected.py
Labels: bug / fix

#93 Add benchmark code and the example with existing graph classification examples
  .github/workflows/testing.yml
  benchmark/kernel/README.md
  benchmark/kernel/main_performance.py
  docs/source/index.rst
  docs/source/modules/profile.rst
  test/profile/test_profile.py
  test/profile/test_utils.py
  test/test_seed.py
  torch_geometric/__init__.py
  torch_geometric/profile/__init__.py
  torch_geometric/profile/profile.py
  torch_geometric/profile/profiler.py
  torch_geometric/profile/utils.py
  torch_geometric/seed.py
Labels: enhancement

#104 Move `HGTLoader` to `torch_geometric.loader` + clean up
  docs/source/modules/loader.rst
  examples/hetero/to_hetero_mag.py
  test/loader/test_hgt_loader.py
  test/loader/test_neighbor_loader.py
  test/nn/dense/test_linear.py
  torch_geometric/data/__init__.py
  torch_geometric/data/hgt_sampler.py
  torch_geometric/loader/__init__.py
  torch_geometric/loader/hgt_loader.py
Labels: enhancement

#108 Rename `AddTrainValTestMask` to `RandomNodeSplit`
  examples/cora.py
  test/transforms/test_random_node_split.py
  torch_geometric/deprecation.py
  torch_geometric/transforms/__init__.py
  torch_geometric/transforms/random_node_split.py
Labels: Priority P0, deprecation

#83 Heterogeneous Graph Tutorial
  docs/source/_figures/hg_example.svg
  docs/source/_figures/hg_example.tex
  docs/source/index.rst
  docs/source/notes/heterogeneous.rst
Labels: documentation

#89 Lazy GNN operators
  test/nn/conv/test_arma_conv.py
  test/nn/conv/test_gmm_conv.py
  test/nn/conv/test_spline_conv.py
  torch_geometric/nn/conv/arma_conv.py
  torch_geometric/nn/conv/cheb_conv.py
  torch_geometric/nn/conv/fa_conv.py
  torch_geometric/nn/conv/feast_conv.py
  torch_geometric/nn/conv/gatv2_conv.py
  torch_geometric/nn/conv/gmm_conv.py
  torch_geometric/nn/conv/graph_conv.py
  torch_geometric/nn/conv/gravnet_conv.py
  torch_geometric/nn/conv/nn_conv.py
  torch_geometric/nn/conv/spline_conv.py
  torch_geometric/nn/conv/supergat_conv.py
  torch_geometric/nn/conv/tag_conv.py
  torch_geometric/nn/conv/utils/cheatsheet.py
  torch_geometric/nn/dense/linear.py
Labels: bug / fix, enhancement

#119 Deprecate `NeighborSampler`
  README.md
  examples/cluster_gcn_reddit.py
  examples/graph_sage_unsup.py
  examples/infomax_inductive.py
  examples/multi_gpu/distributed_sampling.py
  examples/ogbn_products_gat.py
  examples/ogbn_products_sage.py
  examples/pytorch_lightning/graph_sage.py
  examples/reddit.py
  test/loader/test_neighbor_sampler.py
  torch_geometric/data/__init__.py
  torch_geometric/graphgym/loader.py
  torch_geometric/loader/__init__.py
  torch_geometric/loader/neighbor_sampler.py
Labels: bug / fix, Priority P0

#120 Move `torch_geometric.data.DataLoader` to `torch_geometric.loader.DataLoader`
  benchmark/kernel/main_performance.py
  benchmark/kernel/train_eval.py
  benchmark/points/train_eval.py
  docs/source/notes/batching.rst
  docs/source/notes/create_dataset.rst
  docs/source/notes/introduction.rst
  examples/attentive_fp.py
  examples/cluster_gcn_ppi.py
  examples/colors_topk_pool.py
  examples/dgcnn_classification.py
  examples/dgcnn_segmentation.py
  examples/egc.py
  examples/faust.py
  examples/film.py
  examples/gcn2_ppi.py
  examples/geniepath.py
  examples/jit/gin.py
  examples/mem_pool.py
  examples/mnist_graclus.py
  examples/mnist_nn_conv.py
  examples/mnist_voxel_grid.py
  examples/multi_gpu/distributed_batching.py
  examples/mutag_gin.py
  examples/pna.py
  examples/pointnet2_classification.py
  examples/pointnet2_segmentation.py
  examples/ppi.py
  examples/proteins_mincut_pool.py
  examples/proteins_topk_pool.py
  examples/pytorch_lightning/gin.py
  examples/qm9_nn_conv.py
  examples/qm9_pretrained_dimenet.py
  examples/qm9_pretrained_schnet.py
  examples/renet.py
  examples/seal_link_pred.py
  examples/triangles_sag_pool.py
  examples/upfd.py
  test/datasets/test_enzymes.py
  test/datasets/test_planetoid.py
  test/loader/test_dataloader.py
  test/nn/models/test_re_net.py
  test/transforms/test_to_superpixels.py
  torch_geometric/data/__init__.py
  torch_geometric/data/data.py
  torch_geometric/graphgym/loader.py
  torch_geometric/loader/__init__.py
  torch_geometric/loader/dataloader.py
Labels: bug / fix, Priority P0
