Repository vrtex-team/pytorch_geometric, pull requests merged in 2021-05, with the labels that each got.

#6 customized linear layer implementation
  test/nn/dense/test_linear.py
  torch_geometric/nn/dense/__init__.py
  torch_geometric/nn/dense/linear.py
  torch_geometric/nn/inits.py
Labels: enhancement, good first issue

#2 Lazy GNN operator initialization
  test/nn/dense/test_dense_gcn_conv.py
  torch_geometric/nn/conv/eg_conv.py
  torch_geometric/nn/conv/gcn_conv.py
  torch_geometric/nn/conv/hypergraph_conv.py
  torch_geometric/nn/dense/__init__.py
  torch_geometric/nn/dense/dense_gcn_conv.py
Labels: enhancement, good first issue

#1 Heterogeneous Graph Storage Layer
  docs/source/notes/introduction.rst
  test/data/test_batch.py
  test/data/test_data.py
  test/data/test_dataloader.py
  test/data/test_dataset.py
  test/data/test_hetero_data.py
  test/data/test_storage.py
  test/datasets/test_enzymes.py
  test/datasets/test_planetoid.py
  test/transforms/test_add_self_loops.py
  test/transforms/test_constant.py
  test/transforms/test_face_to_edge.py
  test/transforms/test_laplacian_lambda_max.py
  test/transforms/test_one_hot_degree.py
  test/transforms/test_target_indegree.py
  test/transforms/test_two_hop.py
  test/utils/test_convert.py
  torch_geometric/data/__init__.py
  torch_geometric/data/batch.py
  torch_geometric/data/cluster.py
  torch_geometric/data/data.py
  torch_geometric/data/graph_saint.py
  torch_geometric/data/hetero_data.py
  torch_geometric/data/in_memory_dataset.py
  torch_geometric/data/sampler.py
  torch_geometric/data/shadow.py
  torch_geometric/data/storage.py
  torch_geometric/data/view.py
  torch_geometric/deprecation.py
  torch_geometric/io/tu.py
  torch_geometric/typing.py
  torch_geometric/utils/convert.py
Labels: enhancement

#32 Convert AMiner Dataset to new HeteroData format
  examples/metapath2vec.py
  torch_geometric/datasets/aminer.py
Labels: bug / fix
